dataset:
  name: megamarket
  path: "./replay_benchmarks/data/megamarket"

  feature_schema:
    query_column: "user_id"
    item_column: "item_id"
    rating_column: "rating"
    timestamp_column: "datetime"

  preprocess:
    global_split_ratio: 0.1
    val_users_ratio: 0.05
    min_users_per_item: 5
    min_items_per_user: 3